name: Run Python Script

on:
  schedule:
    - cron: '*/1 * * * *' # This will run the script every minute
  workflow_dispatch: # This enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python script.py

    - name: Commit CSV file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.csv
        git commit -m "Add generated CSV file"
        git push
