name: Run Python Script

on:
  schedule:
    - cron: '30 4 * * *'
    
  workflow_dispatch: # This enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script
      run: |
        python script.py

    - name: Commit CSV file
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        git add *.csv
        git commit -m "Scraped from FBREF at $timestamp"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
